news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'article/(?P<article_id>\w+)/$',views.article, name='article'),
]

newsfeed/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin', admin.site.urls, name='admin'),
    url(r'',include('news.urls')),
] \
     + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from django.db import models
#TODO: https://www.berlingskemedia.dk/
# Create your models here.

class Article(models.Model):
    article_title=models.CharField(max_length=128, default=None,blank=True,null=True)
    short_article=models.TextField(max_length=512, default=None,blank=True,null=True)
    full_article=models.TextField(max_length=999999999, default=None,blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" %self.article_title

class ArticleImage(models.Model):
    article=models.ForeignKey(Article,blank=True, null=True, default=None)
    image = models.ImageField(upload_to='pictures')
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" %self.id

news/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *

# Create your views here.
def index(request):
    articles_list = Article.objects.all()[::-1]
    page=request.GET.get('page')

    article_images = ArticleImage.objects.filter(is_main=True)
    paginator=Paginator(articles_list,12)

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)


    return render(request,'html/index.html',locals(), {'articles':articles})


def article(request, article_id):
    article = Article.objects.get(id=article_id)
    return render(request,'html/article.html',locals())

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    {#importing css#}
    <link href="{% static 'static/css/template.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'static/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="static/static/css/template.css"/>

    {#importing js#}
    <script src="{% static 'static/js/script.js' %}" type="text/javascript" rel="script"></script>
    <script src="{% static 'static/js/bootstrap.min.js' %}" type="text/javascript" rel="script"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


    <title>
        {% block title %}
        {% endblock %}
    </title>

</head>
    <body>

        <div class="navbar">
            {% include 'html/navbar.html' %}
        </div>

        <div class="container content">
            {% block content %}
            {% endblock %}
        </div>



        <div class="footer">
            {% include 'html/footer.html' %}
        </div>

    </body>
</html>

templates/html/article.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{ article.article_title }}
{% endblock %}

{% block content %}
    <div class="container text-center">
        <div class="col-xl-12">
            <div class="font-weight-bold text-center">
                <h1>{{ article.article_title }}</h1>
            </div>

            {% for image in article.articleimage_set.all %}
                {% if image.is_main %}
                    <img class="img-thumbnail" src="{{ image.image.url }}">
                {% endif %}
            {% endfor %}
            <div class="text-justify">
                {{ article.full_article }}
            </div>
        </div>
        <div class="text-right small">

            Created: {{ article.created }}
        </div>
        <a href="#" onclick="window.history.back();" class="previous">&#8249;&#8249;- Back to main</a>

    </div>
{% endblock %}

templates/html/footer.html
<footer class="footer">
    <div class="container text-dark">
    <a class="col-sm-1" href="{% url 'index' %}">Home</a>
        <a class="col-sm-2" href="{% url 'index' %}">Home</a>
        <a class="col-sm-3" href="{% url 'index' %}">Home</a>
        </div>
</footer>

templates/html/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Berlingske Media News
{% endblock %}



{% block content %}
    <div class="row">
        {% for article in articles %}
            <div class="col-md-3 article">
                        <div class="text-center container"><b><a class="underline-none" href="{% url 'article' article.id %}"> {{ article.article_title }}

            {% for article_image in article.articleimage_set.all %}
                {% if article_image.is_main %}
                    <img class="img-thumbnail" src="{{ article_image.image.url }}">
                {% endif %}

            {% endfor %}
</a></b></div>
<br/>
                <div class="alert-danger">{{ article.short_article }}</div>
            <div class="text-left small">
            {{ article.created }}
            </div>
            </div>

        {% endfor %}

    </div>



   {% if articles.has_other_pages %}
      <ul class="pagination">
        {% if articles.has_previous %}
            <li class="marging"><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
            {% else %}
      <li class="disabled margin"><span>&laquo;</span></li>
        {% endif %}

    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="marging"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="marging"><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
        {% if articles.has_next %}
      <li class="marging"><a href="?page={{ articles.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled margin"><span>&raquo;</span></li>
    {% endif %}
    </ul>
{% endif %}






{% endblock %}

templates/html/navbar.html
{% load static %}
<div class="nav navbar">
    <a class="nav nav-item nav-link" href="{% url 'index' %}">Home</a>
    <a class="nav nav-item nav-lin" href="/admin" target="_blank">Admin panel</a>
</div>